name: Main.js CI


on:
  push:
    branches: [deploy1]
  pull_request:
    branches: [deploy1]

jobs:
  build:
    runs-on: self-hosted
  
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
  
    # - run: npm install 
    # - run: npm install express-rate-limit
    # - run: npm install express-rate-limit
  # comment
    

    - name: 'Create env file'
      run: |
          echo whoami
          npm install
          touch .env
          echo DB_HOST=${{secrets.DB_HOST}} >> .env
          echo DB_USER=${{secrets.DB_USER}} >> .env
          echo DB_PASS=${{secrets.DB_PASS}} >> .env
          echo DB_NAME=${{secrets.DB_NAME}} >> .env
          echo DB_DIALECT=${{secrets.DB_DIALECT}} >> .env
          echo DB_PORT=${{secrets.DB_PORT}} >> .env
          echo APP_HOST=${{secrets.APP_HOST}} >> .env
          echo PORT=${{secrets.PORT}} >> .env
          
    - name: 'Restart server'
      run: |
          pm2 restart 9
         
         

         
          
